### PR TITLE
Fb error handling

### PR DESCRIPTION
**Pull request by gholibeigian**
Dear Simon

Can you please review our code. We need to merge it to the master branch!

### CODE REVIEW

**Comment by gholibeigian** [comment]
@kokolubilubi see the code!

**Comment by kokolubilubi** [comment]
You should not be so mean to me!

**Comment by kokolubilubi** [comment]
> @kokolubilubi see the code!

You should not use exception everywhere

**Review by kokolubilubi — CHANGES_REQUESTED** [review]
Hey change your code!!!

**Review by kokolubilubi — APPROVED** [review]
there we go!

**Pull request merged**
